# Generated by Django 6.1.1 on 2026-09-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('employer', 'Employer'), ('admin', 'Admin')], default='applicant', max_length=20),
        ),
    ]
