# Generated by Django 6.1.1 on 2026-09-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-date',)},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='date',
        ),
    ]
