# Generated by Django 6.1.1 on 2026-09-29 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
