# Generated by Django 6.1.1 on 2026-09-22 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0004_job_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('SKILL', 'Skill'), ('EXPERIENCE', 'Experience'), ('EDUCATION', 'Education'), ('CERTIFICATION', 'Certification'), ('KNOWLEDGE', 'Knowledge'), ('LANGUAGE', 'Language'), ('BEHAVIORAL', 'Behavioral'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_app_criterion',
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_application.job'),
        ),
        migrations.CreateModel(
            name='JobCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximum_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_criteria', to='job_application.criterion')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='job_application.job')),
            ],
            options={
                'db_table': 'main_app_job_criterion',
                'constraints': [models.UniqueConstraint(fields=('job', 'criterion'), name='unique_job_criterion')],
            },
        ),
    ]
