# Generated by Django 6.1.1 on 2026-09-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0005_criterion_alter_application_job_jobcriterion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'verbose_name': 'Criterion', 'verbose_name_plural': 'Criteria'},
        ),
        migrations.AlterModelOptions(
            name='jobcriterion',
            options={'verbose_name': 'Job criterion', 'verbose_name_plural': 'Job criteria'},
        ),
    ]
