# Generated by Django 6.1.1 on 2026-09-24 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0006_alter_criterion_options_alter_jobcriterion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'main_app_requirement',
                'ordering': ('description',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='jobcriterion',
            name='unique_job_criterion',
        ),
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ('name',), 'verbose_name': 'Criterion', 'verbose_name_plural': 'Criteria'},
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AddField(
            model_name='criterion',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='job_application.job'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='job_application.criterion'),
        ),
        migrations.DeleteModel(
            name='JobCriterion',
        ),
    ]
