# Generated by Django 6.1.1 on 2026-09-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0010_job_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('SCREENED', 'Screened'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected')], default='RECEIVED', max_length=20),
        ),
    ]
