# Generated by Django 6.1.1 on 2026-09-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0011_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
