# Generated by Django 6.1.1 on 2026-10-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SPECIFIC', 'Specific')], default='GENERAL', max_length=8),
        ),
    ]
