# Generated by Django 6.1.1 on 2026-10-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='expected_answer',
            field=models.TextField(blank=True),
        ),
    ]
