# Generated by Django 6.1.1 on 2026-09-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_application', '0007_requirement_remove_jobcriterion_unique_job_criterion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('overall_score', models.PositiveIntegerField()),
                ('overall_comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_result', to='job_application.application')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningCriterionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField()),
                ('evidence', models.TextField()),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_application.requirement')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='application_screening.screeningresult')),
            ],
        ),
    ]
