# Generated by Django 6.1.1 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningresult',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
