# Generated by Django 6.1.1 on 2026-10-03 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_screening', '0002_alter_screeningresult_file_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresult',
            name='review_method',
            field=models.CharField(choices=[('AI', 'AI-assisted'), ('MANUAL', 'Manual')], default='AI', max_length=10),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
